### PR TITLE
feat: better LOGIN_FAILED 🔊

### PR DESCRIPTION
**Pull request by gregorylegarec**

### CODE REVIEW

**Comment by ptbrowne** [comment]
I think removing the catch in the index should be good enough.

```
.catch(err => {
      console.log(err.stack)
    })
```

should be good enough. The BaseKonnector automatically attach a `catch` callback that takes care of doing `terminate()` in case of an error.

**Comment by doubleface** [comment]
@ptbrowne Good catch, i will fix this

**Comment by doubleface** [comment]
@ptbrowne  oups, it is a cozy-konnector-libs v2 connector but it will be migrated soon

**Comment by doubleface** [comment]
@ptbrowne sorry, wrong konnector, I will fix it

**Pull request merged**
